Small changes
VertisanPRO/Nexus pull request #82
Opened 2022-08-27 13:42 UTC by PadowYT2

* After clicking `Update` redirect user to link without `?nexusUpgrade`
* A little formatting
* Remove caching code from `upgrade.php`

2022-08-27 23:39 UTC, Sylensky requested changes

2022-08-27 23:39 UTC, Sylensky commented on custom/templates/Nexus/template_settings/upgrade.php
> -$cache->store('update_check_nexus', $update_check_nexus, 3600);
newline at end of file missing.

2022-08-27 23:54 UTC, Sylensky commented on custom/templates/Nexus/template_settings/upgrade.php
> -$cache->store('update_check_nexus', $update_check_nexus, 3600);
i am not sure if this is fine here.

2022-08-28 05:03 UTC, PadowYT2 commented on custom/templates/Nexus/template_settings/upgrade.php
> -$cache->store('update_check_nexus', $update_check_nexus, 3600);
it is completly fine

2022-08-30 20:14 UTC, merged